// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjVTQMr0-1H37KO7bepEeiCFEhd-xANg',
    appId: '1:971537987494:web:fef288d9457617a65d8167',
    messagingSenderId: '971537987494',
    projectId: 'telemedicine-a79f4',
    authDomain: 'telemedicine-a79f4.firebaseapp.com',
    storageBucket: 'telemedicine-a79f4.firebasestorage.app',
    measurementId: 'G-FL5N4VBBHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7P2mgSBPVk15SSJupw-kTKgAp-T3hxoo',
    appId: '1:971537987494:android:713437deec820cc35d8167',
    messagingSenderId: '971537987494',
    projectId: 'telemedicine-a79f4',
    storageBucket: 'telemedicine-a79f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmGfaZHMPXnwI2b1vpmfdI32OnnGVWkw',
    appId: '1:971537987494:ios:4dc3c0321d3c79b45d8167',
    messagingSenderId: '971537987494',
    projectId: 'telemedicine-a79f4',
    storageBucket: 'telemedicine-a79f4.firebasestorage.app',
    iosBundleId: 'com.telemedicine.mobile.telemedicinemobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYmGfaZHMPXnwI2b1vpmfdI32OnnGVWkw',
    appId: '1:971537987494:ios:4dc3c0321d3c79b45d8167',
    messagingSenderId: '971537987494',
    projectId: 'telemedicine-a79f4',
    storageBucket: 'telemedicine-a79f4.firebasestorage.app',
    iosBundleId: 'com.telemedicine.mobile.telemedicinemobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbjVTQMr0-1H37KO7bepEeiCFEhd-xANg',
    appId: '1:971537987494:web:6457b89f5077e24a5d8167',
    messagingSenderId: '971537987494',
    projectId: 'telemedicine-a79f4',
    authDomain: 'telemedicine-a79f4.firebaseapp.com',
    storageBucket: 'telemedicine-a79f4.firebasestorage.app',
    measurementId: 'G-VLK5GBWPN9',
  );
}
