# Sync GOOGLE_MAPS_API_KEY from repo root .env.local into mobile native config.
$ErrorActionPreference = "Stop"
$mobileRoot = Split-Path -Parent $PSScriptRoot
$repoRoot = Split-Path -Parent $mobileRoot
$envFile = Join-Path $repoRoot ".env.local"

if (-not (Test-Path $envFile)) {
    Write-Host "No .env.local at $envFile"
    exit 1
}

$key = $null
Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()
    if ($line -match '^(?:GOOGLE_MAPS_API_KEY|VITE_GOOGLE_MAPS_API_KEY)\s*=\s*(.+)$') {
        $key = $Matches[1].Trim().Trim('"').Trim("'")
    }
}

if (-not $key -or $key.Length -lt 20) {
    Write-Host "GOOGLE_MAPS_API_KEY not found in .env.local"
    exit 1
}

$suffix = $key.Substring($key.Length - 6)
Write-Host "Maps key ...$suffix"

# Android local.properties (preserve sdk.dir / flutter.sdk)
$localProps = Join-Path $mobileRoot "android\local.properties"
$lines = @()
if (Test-Path $localProps) {
    $lines = @(Get-Content $localProps | Where-Object {
        $_ -notmatch '^\s*GOOGLE_MAPS_API_KEY\s*='
    })
}
$hasMaps = $lines | Where-Object { $_ -match '^\s*GOOGLE_MAPS_API_KEY\s*=' }
if (-not $hasMaps) {
    $lines += "GOOGLE_MAPS_API_KEY=$key"
} else {
    $lines = @($lines | ForEach-Object {
        if ($_ -match '^\s*GOOGLE_MAPS_API_KEY\s*=') { "GOOGLE_MAPS_API_KEY=$key" } else { $_ }
    })
}
$repoFlutter = Join-Path $repoRoot ".flutter-sdk"
if ((Test-Path (Join-Path $repoFlutter "bin\flutter.bat"))) {
    $flutterSdkLine = "flutter.sdk=$($repoFlutter -replace '\\', '\\')"
    if ($lines | Where-Object { $_ -match '^\s*flutter\.sdk\s*=' }) {
        $lines = @($lines | ForEach-Object {
            if ($_ -match '^\s*flutter\.sdk\s*=') { $flutterSdkLine } else { $_ }
        })
    } else {
        $lines += $flutterSdkLine
    }
}
if (-not ($lines | Where-Object { $_ -match '^\s*sdk\.dir\s*=' })) {
    $androidHome = $env:ANDROID_HOME
    if (-not $androidHome) { $androidHome = "$env:LOCALAPPDATA\Android\sdk" }
    if (Test-Path $androidHome) {
        $lines += "sdk.dir=$($androidHome -replace '\\', '\\')"
    }
}
Set-Content -Path $localProps -Value $lines -Encoding UTF8
Write-Host "Updated android/local.properties"

# iOS MapsConfig.plist
$mapsPlist = Join-Path $mobileRoot "ios\Runner\MapsConfig.plist"
$plistXml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>API_KEY</key>
	<string>$key</string>
</dict>
</plist>
"@
[System.IO.File]::WriteAllText($mapsPlist, $plistXml)
Write-Host "Updated ios/Runner/MapsConfig.plist"

# Dart maps_key.dart
$mapsKeyDart = Join-Path $mobileRoot "lib\core\maps_key.dart"
$dartContent = @"
/// Auto-generated by scripts/sync_maps_key.ps1
class MapsKey {
  MapsKey._();
  static const String resolved = '$key';
}
"@
[System.IO.File]::WriteAllText($mapsKeyDart, $dartContent)
Write-Host "Updated lib/core/maps_key.dart"

# dart_defines.json (merge maps key; preserve API_URL + Google OAuth client)
$definesFile = Join-Path $mobileRoot "dart_defines.json"
$defaultApiUrl = "https://www.bytzgo.net"
foreach ($line in (Get-Content $envFile -ErrorAction SilentlyContinue)) {
    $t = $line.Trim()
    if ($t -match '^\s*MOBILE_API_URL\s*=\s*(.+)$') {
        $defaultApiUrl = $Matches[1].Trim().Trim('"').Trim("'").TrimEnd('/')
        break
    }
    if ($t -match '^\s*VITE_API_URL\s*=\s*(.+)$') {
        $v = $Matches[1].Trim().Trim('"').Trim("'").TrimEnd('/')
        # Web dev URLs (localhost / 127.0.0.1) do not work on Android emulator.
        if ($v -and $v -notmatch '^(https?://)?(localhost|127\.0\.0\.1)(:\d+)?') {
            $defaultApiUrl = $v
        }
    }
}

$defines = @{
    GOOGLE_MAPS_API_KEY = $key
    API_URL = $defaultApiUrl
    GOOGLE_WEB_CLIENT_ID = "568487483843-99c0bucqujokf2h1vtmno1ku0jea7b4f.apps.googleusercontent.com"
}
if (Test-Path $definesFile) {
    try {
        $existing = Get-Content $definesFile -Raw | ConvertFrom-Json
        if ($existing.API_URL) { $defines.API_URL = $existing.API_URL }
        if ($existing.GOOGLE_WEB_CLIENT_ID) { $defines.GOOGLE_WEB_CLIENT_ID = $existing.GOOGLE_WEB_CLIENT_ID }
    } catch { }
}
$googleClient = $null
Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()
    if ($line -match '^(?:GOOGLE_WEB_CLIENT_ID|VITE_GOOGLE_CLIENT_ID)\s*=\s*(.+)$') {
        $googleClient = $Matches[1].Trim().Trim('"').Trim("'")
    }
}
if ($googleClient) { $defines.GOOGLE_WEB_CLIENT_ID = $googleClient }
$json = ($defines | ConvertTo-Json -Depth 3)
[System.IO.File]::WriteAllText($definesFile, $json)
Write-Host "Wrote dart_defines.json"
Write-Host "Run: flutter run --dart-define-from-file=dart_defines.json"
